version: "3.9"
services:
  volleyplay_slot_catcher:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: volleyplay-slot-catcher:latest
    container_name: "volleyplay-slot-catcher"
    depends_on:
      selenium:
        condition: service_healthy
    networks:
      - my-network
    env_file:
      - path: ./.env
        required: true
    volumes:
      - .:/app
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chromium:latest # Для AMD64
# image: seleniarm/standalone-chromium:latest # Для ARM64
    container_name: selenium-container
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "4444:4444"  # Selenium WebDriver API
      - "7900:7900"  # VNC Viewer
    networks:
      - my-network
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_DETECT_DRIVERS=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

networks:
  my-network: